---
title: "Vignette Title"
author: "Tony Landas"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Explanation of LATools Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Data
```{r}
library("LATools")
#>he data accesssible from within this package is previewed in this section.
#>Flight Data
flights <-read.csv("http://users.stat.umn.edu/~almquist/3811_examples/all_alaska_flights.csv")
str(flights)
#>Random Data
d <- read.table(url("http://www.stat.umn.edu/geyer/3701/data/q1p4.txt"), header = TRUE)
str(d)
#>Data from GapMinder
gap <-read.csv("http://users.stat.umn.edu/~almquist/3811_examples/gapminder2007ex.csv", header = TRUE)
str(gap)
```
## Functions

```{r}
#> Several Functions from previous assignments as well as a couple new additions have been added to the LATools package. They can be examined in this section.

#> Log Likelihood
#logL(d, binomial, c(-100, 100))
#> logL calculates the maximum likelihood estimator(MLE) when given a specfic dataset, probability distribution and interval, as seen in the example with a binomial distribution.

#> GGPlotWrapper
#ggplotW(flights, "dep_time", "dep_delay", color = blue)
#> Using the ggplot2 library the GGPlot Wrapper is able to graph two variables against each other within the same dataset.

#> Matrix Adjuster
#adjMat(flights, "dep_time")
#> The matrix adjuster uses dpylr on a user selected column from a user selected datset

#> Measures of Spread
#spread(d)
#> Calculates the population mean, variance and standard deviation for user given dataset

#> Measures of Spread w/ Checks
#spreadCheck(d)
#>Similar to spread, spreadCheck checks the data given make sure that it is numeric, finite, etc.. 

#> MyApply
#myapply(d, 1, mean)
#> Myapply, is similar to other apply functions currently in R and it applies a function such as mean in the example to a specfic margin within the user given dataset
```
